using System;
using System.ComponentModel;

namespace WebToolkit.Contracts
{
    public interface ILock
    {
        Action DoWork { get; }
        /// <summary>
        /// Executes lock
        /// </summary>
        void Run();
    }

    public interface ILock<TResult> : ILock, INotifyPropertyChanged
    {
        new Func<TResult, TResult> DoWork { get; }

        /// <summary>
        /// Value generated by DoWork
        /// </summary>
        TResult Value { get; }
    }
}